/* List of halophiles according to the literature */
DROP TABLE IF EXISTS halophiles;

CREATE TABLE halophiles (
	species varchar(75) NOT NULL DEFAULT ''
);

INSERT INTO halophiles (species) VALUES
('Dichotomicrobium thermohalophilus'),
('Thermohalobacter berrensis'),
('Haloanaerobium praevalens'),
('Haloanaerobium alcaliphilum'),
('Haloanaerobium acetyethylicum'),
('Haloanaerobium salsuginis'),
('Haloanaerobium saccharolyticum'),
('Haloanaerobium congolense'),
('Haloanaerobium lacusrosei'),
('Haloanaerobium kushneri'),
('Haloanaerobium fermentans'),
('Halocella cellulosilytica'),
('Halothermothrix orenii'),
('Natrionella acetigenica'),
('Halobacteroides halobius'),
('Halobacteroides elegans'),
('Acetohalobium arabatiania'),
('Haloanaerobacter chitinivorens'),
('Haloanaerobacter lacunarum'),
('Haloanaerobacter salinarius'),
('Orenia marismortui'),
('Orenia salinaria'),
('Orenia sivashensis'),
('Halonatronum saccharophilum'),
('Natrionella acetigena'),
('Sporhalobacter lortetii'),
('Bacillus halophilus'),
('Bacillus haloalkaliphilus'),
('Gracibacillus halotolerans'),
('Gracibacillus dipsosauri'),
('Halobacillus halophilus'),
('Halobacillus literalis'),
('Halobacillus thailandensis'),
('Salibacillus salexigens'),
('Salibacillus marismortui'),
('Oceanobacillus iheyensis'),
('Tindallia magadiensis'),
('Clostridium halophilus'),
('Desulfotomaculum halophilus'),
('Salinicoccus roseus'),
('Sailinicoccus hispanicus'),
('Marinococcus halophilus'),
('Marinococcus albus'),
('Tetragenococcus halophilus'),
('Tetragenococcus muraticus'),
('Nesterenkonia halobia'),
('Actinopolyspora halophila'),
('Actinopolyspora mortivallis'),
('Actinopolyspora iraqiensis'),
('Nocardiopsis lucentensis'),
('Nocardiopsis halophila'),
('Nocardiopsis kunsanensis'),
('Flavobacterium salegens'),
('Salinibacter ruber');
