/* List of psychrophiles according to the literature */
DROP TABLE IF EXISTS psychrophiles;

CREATE TABLE psychrophiles (
	species varchar(75) NOT NULL DEFAULT ''
);

INSERT INTO psychrophiles (species) VALUES
('Colwellia hadaliensis'), 
('Colwellia piezophila'),
('Moritella japonica'),
('Moritella yayanosii'),
('Moritella profunda'),
('Moritella abyssi'),
('Psychromonas kaikoae'),
('Psychromonas hadalis'),
('Psychromonas profunda'),
('Colwellia psychrerythraea'),
('Colwellia demingiae'),
('Colwellia hornerae'),
('Colwellia rossensis'),
('Colwellia maris'),
('Glaciecola punicea'),
('Glaciecola pallidula'),
('Glaciecola psychrophila'),
('Moritella marina'),
('Moritella dasanensis'),
('Moritella viscosa'),
('Psychrobacter glacincola'),
('Psychrobacter fozii'),
('Psychrobacter frigidicola'),
('Psychrobacter luti'),
('Psychromonas antarctica'),
('Psychromonas ingrahamii'),
('Psychromonas boydii'),
('Psychromonas marina'),
('Shewanella abyssi'),
('Shewanella surugensis'),
('Shewanella sediminis'),
('Shewanella halifaxensis'),
('Shewanella atlantica'),
('Shewanella canadensis'),
('Shewanella benthica'),
('Shewanella psychrophila'),
('Shewanella violacea'),
('Shewanella gelidimarina'),
('Shewanella livingstonensis'),
('Shewanella spongiae'),
('Desulfuromonas svalbardensis'),
('Desulfuromonas ferrireducens'),
('Desulfofrigus oceanense'),
('Desulfofaba gelida'),
('Desulfotalea psychrophila'),
('Flavobacterium frigidarium'),
('Flavobacterium limicola'),
('Flavobacterium omnivorum'),
('Flavobacterium xinjiangense'),
('Flavobacterium micromati'),
('Flavobacterium antarcticum'),
('Flavobacterium segetis'),
('Flavobacterium weaverense'),
('Psychroflexus torquis'),
('Deinococcus frigens'),
('Deinococcus marmoris'),
('Deinococcus saxicola'),
('Deinococcus radiomollis'),
('Deinococcus claudionis'),
('Deinococcus altitudinis'),
('Deinococcus alpinitundrae');
